### ISSUE TITLE
action # vendimia is only processing last campo of last bodega, not previous records

### ISSUE THREAD

**Issue by Japoivvb** [IIH10/ActVinicolaJava_IvanIzqHer#3]
1. when vendimia is processed previous records are not being processed, e.g. vid 3,4,17,18

2. set issue label as bug to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 
e.g. #1 adds incremental id logic

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by IIH10** [comment]
![image](https://github.com/IIH10/ActVinicolaJava_IvanIzqHer/assets/137720468/3a05b669-d6a8-4141-9771-38fac5a52f97)

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
