### ISSUE TITLE
add new field recolectado to campo model 

### ISSUE THREAD

**Issue by Japoivvb** [IIH10/ActVinicolaJava_IvanIzqHer#4]
1. add recolectado attribute to campo model, it sets false and changes true after vendimia

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by IIH10** [comment]
![image](https://github.com/IIH10/ActVinicolaJava_IvanIzqHer/assets/137720468/e9a28a1d-127d-48a6-b971-990a0f8d80a9)

El campo solo es recolectado si tiene viñas, por ello el campo 4 al no tener viñas asociadas no es recolectado, quitando la verificación de si tiene viñas o no todos los campos pasarían a true

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
