### ISSUE TITLE
add new method to show all vid.cantidad group by Campo

### ISSUE THREAD

**Issue by Japoivvb** [IIH10/ActVinicolaJava_IvanIzqHer#5]
1. after current showAllCampos() create a new method showCantidadVidByCampo()

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by IIH10** [comment]
Salida de consola del nuevo método:
![image](https://github.com/IIH10/ActVinicolaJava_IvanIzqHer/assets/137720468/c02d7140-c98d-4dbd-bd5a-f532632f0ad5)

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
