### ISSUE TITLE
migrate application from SQL database to NoSQL database

### ISSUE THREAD

**Issue by Japoivvb** [IIH10/ActVinicolaJava_IvanIzqHer#6]
1. modify application to use only mongoDB, remove Hibernate(MySQL) sentence once everything is working

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot(from each collection) in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by IIH10** [comment]
![image](https://github.com/IIH10/ActVinicolaJava_IvanIzqHer/assets/137720468/6b4ce118-7c99-4d05-b240-c7a489ef0781)
![image](https://github.com/IIH10/ActVinicolaJava_IvanIzqHer/assets/137720468/a425bc1c-8096-470e-a41e-8e2f6ef354df)
![image](https://github.com/IIH10/ActVinicolaJava_IvanIzqHer/assets/137720468/2040dc5e-cce0-4520-bde9-256ec2464272)
![image](https://github.com/IIH10/ActVinicolaJava_IvanIzqHer/assets/137720468/1038c5a6-37c9-4e1b-8c90-7f6d32fc7e2b)
![image](https://github.com/IIH10/ActVinicolaJava_IvanIzqHer/assets/137720468/c9bc7a8b-ecc1-4543-816e-ae002e53150d)

**Comment by IIH10** [comment]
![image](https://github.com/IIH10/ActVinicolaJava_IvanIzqHer/assets/137720468/7692d152-d020-4764-a9b3-ee8af1add803)
![image](https://github.com/IIH10/ActVinicolaJava_IvanIzqHer/assets/137720468/31871374-6ee8-4ecb-b07b-df70a78cb0a9)
![image](https://github.com/IIH10/ActVinicolaJava_IvanIzqHer/assets/137720468/e92ee2a3-96f2-4d86-bbca-b820aab1426d)
![image](https://github.com/IIH10/ActVinicolaJava_IvanIzqHer/assets/137720468/62dbaeff-b9a3-4374-ae3e-8e0012cedf15)
![image](https://github.com/IIH10/ActVinicolaJava_IvanIzqHer/assets/137720468/10a77d48-52b8-4869-b887-ba5876942d2a)

**Comment by Japoivvb** [comment]
1. ok
2. ok
3. ok
4. ok
5. ok
merge code to main branch if you can
